image: blang/latex
build:
  script:
    - latexmk -pdf -cd docs/dissertation/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"
test:
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip3 install -r requirements.txt
    - python3 manage.py test student_feedback_app
