# Generated by Django 2.1.2 on 2019-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='colour',
            field=models.CharField(default='#009999', max_length=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_token',
            field=models.CharField(default='', max_length=20),
        ),
    ]
