# Generated by Django 2.1.2 on 2018-11-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(max_length=40, verbose_name='Subject'),
        ),
    ]
