# Generated by Django 2.1.3 on 2019-01-09 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_with_class',
            fields=[
                ('className', models.CharField(default='No class', max_length=200)),
                ('date_given', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('message', models.CharField(default='No message', max_length=200)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'student_feedback_app_feedback_with_class',
                'managed': False,
            },
        ),
    ]
