# Generated by Django 2.1.2 on 2018-10-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='usernameSlug',
            new_name='lecturer_slug',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='usernameSlug',
            new_name='student_slug',
        ),
        migrations.AddField(
            model_name='class',
            name='unique_code',
            field=models.CharField(default='AAA01', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_ID',
            field=models.CharField(default='0000000', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
