# Generated by Django 2.1.2 on 2019-02-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achiev', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_feedback_app.Category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_feedback_app.StudentProfile')),
            ],
        ),
    ]
