# Generated by Django 2.1.2 on 2018-11-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='datetime',
            new_name='datetime_given',
        ),
    ]
