# Generated by Django 2.1.2 on 2018-11-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('text', models.CharField(default='No message', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='optional_message',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Empty', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_feedback_app.Category'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='pre_defined_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_feedback_app.Message'),
        ),
    ]
