# Generated by Django 2.1.2 on 2019-02-13 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0002_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achiev',
            field=models.CharField(max_length=100, validators=[django.core.validators.int_list_validator]),
        ),
    ]
