# Generated by Django 2.1.2 on 2018-11-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0002_auto_20181124_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Empty', max_length=20, primary_key=True, serialize=False),
        ),
    ]
