# Generated by Django 2.1.2 on 2018-11-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0002_auto_20181103_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
