# Generated by Django 2.1.3 on 2018-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0002_auto_20181103_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_nb',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
