# Generated by Django 2.1.2 on 2018-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0002_auto_20181112_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_token',
            field=models.CharField(default='', max_length=7),
        ),
    ]
