# Generated by Django 2.1.2 on 2018-11-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0002_auto_20181116_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='optional_message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
