# Generated by Django 2.1.3 on 2019-02-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0002_auto_20190206_1420'),
        ('student_feedback_app', '0002_auto_20190206_1356'),
    ]

    operations = [
    ]
