# Generated by Django 2.1.2 on 2018-11-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0003_auto_20181103_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
