# Generated by Django 2.1.2 on 2018-11-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0003_auto_20181103_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_image.jpg', upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_image.jpg', upload_to='profile_pictures'),
        ),
    ]
