# Generated by Django 2.1.2 on 2018-11-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0003_auto_20181124_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
