# Generated by Django 2.1.3 on 2018-11-03 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0003_auto_20181103_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='unique_code',
            field=models.CharField(default=uuid.uuid1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_nb',
            field=models.CharField(default=uuid.uuid1, max_length=20, primary_key=True, serialize=False),
        ),
    ]
