# Generated by Django 2.1.3 on 2018-11-06 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0003_auto_20181103_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_given',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
