# Generated by Django 2.1.2 on 2018-11-04 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0004_auto_20181104_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='which_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_feedback_app.Class'),
        ),
    ]
