# Generated by Django 2.1.3 on 2018-11-03 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0004_auto_20181103_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='username',
            field=models.CharField(default=uuid.uuid1, max_length=40, primary_key=True, serialize=False),
        ),
    ]
