# Generated by Django 2.1.2 on 2018-11-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0004_auto_20181124_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
