# Generated by Django 2.1.3 on 2018-11-06 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0005_auto_20181106_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_given',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
