# Generated by Django 2.1.2 on 2019-02-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0005_auto_20190213_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='achiev',
        ),
        migrations.AddField(
            model_name='achievement',
            name='achiev',
            field=models.ManyToManyField(to='student_feedback_app.Course'),
        ),
    ]
