# Generated by Django 2.1.2 on 2018-11-04 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0005_feedback_which_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
