# Generated by Django 2.1.2 on 2018-11-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0005_auto_20181124_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='group_fb',
            field=models.BooleanField(default=False),
        ),
    ]
