# Generated by Django 2.1.2 on 2018-11-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0006_feedback_group_fb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='group_fb',
        ),
    ]
