# Generated by Django 2.1.2 on 2018-11-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0006_feedback_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.CharField(default='No message', max_length=200),
        ),
    ]
