# Generated by Django 2.1.3 on 2018-11-06 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0006_auto_20181106_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_given',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 22, 26, 51, 275601)),
        ),
    ]
