# Generated by Django 2.1.2 on 2018-11-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0004_class_class_description'),
        ('student_feedback_app', '0007_feedback_message'),
    ]

    operations = [
    ]
