# Generated by Django 2.1.3 on 2018-11-06 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0007_auto_20181106_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_given',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
