# Generated by Django 2.1.2 on 2018-11-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0009_merge_20181107_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='datetime',
        ),
    ]
