# Generated by Django 2.1.2 on 2018-11-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_feedback_app', '0010_remove_feedback_datetime'),
        ('student_feedback_app', '0008_merge_20181107_1338'),
    ]

    operations = [
    ]
